tcp_host: "localhost"
tcp_port: 8080
websocket_host: "0.0.0.0"
websocket_port: 8000
log_level: "INFO"
max_connections: 1000
buffer_size: 8192
enable_ssl: false
ssl_cert: null
ssl_key: null
metrics_enabled: true
hot_reload: true
development_mode: false
log_path: "logs"
tcp_timeout: 30.0
tcp_retry_attempts: 3
enable_metrics: true
enable_cache: true
